### PR TITLE
Rewrite of Exolix for [comercial grade] software products

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
[i] Title update

**Comment by ghost** [comment]
@AndrewDisco and @77Z mind reviewing this with me 
there is some unfinished code, but what ever seems finished just skim over it and see if there are any bad practices etc...

**Comment by AndrewDisco** [comment]
I'm checking it right now

**Comment by ghost** [comment]
👍🏽

**Review by AndrewDisco — APPROVED** [review]
It all looks good. I couldn’t find any substantial errors in your code/writing.

**Review by decahedron1 — APPROVED** [review]
i approb👍

**Comment by ghost** [comment]
Thanks @sudo-carson ... hold on, how did u-how did u do that

**Pull request merged**
