### PR TITLE
Added OS notice

### PR DESCRIPTION
**Pull request by NekaouMike**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Android and IOS are also supported, 
Some extra platforms include XBoxOS and Playstation

**Review by ghost — APPROVED** [review]
Looks good to me!

**Review by 77Z — APPROVED** [review]
INCREDIBLE JOB

**Review by GearBoxFox — APPROVED** [review]
Sweet, looks all good to me.

**Pull request merged**
